# Configurations used for downloading OSM extracts

[server]
url = "https://download.geofabrik.de"


[regions]
hamburg = "europe/germany/hamburg"
darmstadt = "europe/germany/hessen"
frankfurt = "europe/germany/hessen"
tallinn = "europe/estonia"


[versions]
2018 = "180101.osm.pbf"
2019 = "190101.osm.pbf"
2020 = "200101.osm.pbf"
2021 = "210101.osm.pbf"
2022 = "220101.osm.pbf"
2023 = "230101.osm.pbf"
2024 = "240101.osm.pbf"
2025 = "250101.osm.pbf"
latest = "latest.osm.pbf"


# Hamburg configurations

[hamburg.areas]
tags.boundary = "administrative"
tags.admin_level = "9"

[hamburg.clip]
bbox = [9.5, 10.4, 53.3, 53.75]

[hamburg.places]
entity = "node"
tags.natural = "tree"
tags."genus:de" = "Eiche"


# Darmstadt configurations

[darmstadt.areas]
tags.boundary = "administrative"
tags.admin_level = "9"

[darmstadt.clip]
tags.boundary = "administrative"
tags.admin_level = "6"
tags.name = "Darmstadt"

[darmstadt.places]
keys = ["name"]
tags.amenity = "post_office"


# Frankfurt configurations

[frankfurt.areas]
tags.boundary = "administrative"
tags.admin_level = "10"

[frankfurt.clip]
tags.boundary = "administrative"
tags.admin_level = "6"
tags.name = "Frankfurt am Main"

[frankfurt.places]
keys = ["surveillance"]


# Tallinn configurations

[tallinn.areas]
tags.boundary = "administrative"
tags.admin_level = "9"

[tallinn.clip]
tags.boundary = "administrative"
tags.admin_level = "7"
tags.name = "Tallinn"

[tallinn.places]
keys = ["name", "artwork_type"]
tags.tourism = "artwork"
